### ISSUE TITLE
[BUG] Addserver command doesn't works

### ISSUE THREAD

**Issue by chocochocotorta** [Retr0-01/srcds-discord-bot#1]
**Description**
When using /addserver Slash Command, it always gives the same error: "There was an error while executing this command!". 

**Reproduce**
1. Edit config.json with my Server ID.
2. Host BOT with PM2.
3. Use /addserver with my TF2 Server IP + RCON.
4. See error.

**Expected behavior**
Server should be added normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/45585078/182073957-44ddb03d-2dea-4a09-acbf-faa32679e9be.png)

**Additional context**
OS: Ubuntu 20.04.4 LTS
Node.js Version: v16.15.1

**Comment by Retr0-01** [comment]
Can you please post your ``error.log`` which is inside the logs folder? 

Please ensure you have stripped out any personal data (e.g. personal names in paths).

**Comment by chocochocotorta** [comment]
I was able to fix it, the solution was that the servers folder did not exist in /src/!

Also, i have a question: /server command is to show if the server is on or off? or is it supposed to show the connected players?

Many thanks <3

**Comment by Retr0-01** [comment]
Glad you managed to fix it. I should probably add a gitkeep file in there too so it doesn't get ignored by git. 

The server command currently just shows the added server's address and other info like who added the server. It doesn't show any real-time information for now, but that is something that can be implemented as part of the next major release.

**Comment by chocochocotorta** [comment]
ohhh pretty nice, thanks for the help!
